export const ADMINS_SCENE = {
   STARTED: 'ADMIN_STARTED_SCENE',
   SETTINGS: 'ADMIN_SETTINGS_SCENE',
}
export const USERS_SCENE = {
   STARTED: 'USER_STARTED_SCENE',
   ABOUT: 'USER_ABOUT_SCENE',
   BONUS: 'USER_BONUS_SCENE',
   PRODUCTS: 'USER_PRODUCTS_SCENE',
   ORDERS: 'USER_ORDERS_SCENE',
   CART: 'USER_CART_SCENE',
   CLOSED: 'USER_CLOSED_SCENE',
}