export const ADMINS_SCENE = {
   STARTED: 'ADMIN_STARTED_SCENE',
   SETTINGS: 'ADMIN_SETTINGS_SCENE',
}
export const USERS_SCENE = {
   STARTED: 'USER_STARTED_SCENE',
   ABOUT: 'USER_ABOUT_SCENE',
   ORDERS: 'USER_ORDERS_SCENE',
}